#knife4j配置
knife4j:
  # 是否是生产环境
  production: false

spring:

  # mysql 配置
  datasource:
    url: jdbc:mysql://10.20.54.162:3306/ztb_perm?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: xdcplus.com

  # redis 缓存配置
  redis:
    host: localhost
    port: 6379
    database: 1


