logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

spring:

  profiles:
    active: ${ACTIVE_NAME}

  # mysql 配置
  datasource:
    # 数据源/连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
    # 数据库驱动名称
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    schema:
      - classpath:sql/flowable.sql
      - classpath:sql/synergy.sql
      - classpath:sql/dictionary.sql

    druid:
      # 定义初始连接数
      initialSize: 1
      # 定义最小空闲 minIdle=1
      minIdle: 3
      # 定义最大连接数
      maxActive: 300
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      # 验证使用的SQL语句
      validationQuery: select 'x'
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      testWhileIdle: true
      # 借出连接时不要测试，否则很影响性能
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      # 指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      db-type: mysql

  # redis 缓存配置
  cache:
    redis:
      time-to-live: 60s
    type: redis
  redis:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 300
        max-idle: 10
        min-idle: 5
        max-wait: 10000ms


#knife4j配置
knife4j:
  enable: true

#swagger公共信息
swagger:
  title: 招投标项目-工作流引擎服务
  base-packages: com.xdcplus.workflow.controller
  description: 招投标项目-工作流引擎服务接口文档系统
  version: 2.1.0
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: https://www.apache.org/licenses/LICENSE-2.0.html
  base-path: /**
  contact:
    name: 贾荣
    email: Rong.Jia@xdcplus.com
    url: https://www.xdcplus.com

# 线程池
task:
  pool:
    # 核心线程池大小
    corePoolSize: 5
    # 最大线程数
    maxPoolSize:  300
    # 队列容量
    keepAliveSeconds: 500
    # 活跃时间
    queueCapacity:  50

# mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      # 主键ID 生成策略
      id-type: assign_id
      # 表名前缀
      table-prefix: xdc_t_
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mappers/**/*.xml

# 分页
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true














