version: "3"

services:
  eureka:
    image: 10.20.54.132:8000/ztb-sd/eureka:latest
    restart: always
    container_name: eureka
    ports:
      - 8761:8761
    env_file:
      - ./conf/common
    expose:
      - 8761
    volumes:
      - /data/ztb-sd/eureka:/logs
    networks:
      - ztb_net

  workflow-service:
    image: 10.20.54.132:8000/ztb-sd/workflow-service:latest
    restart: always
    container_name: workflow-service
    env_file:
      - ./conf/common
      - ./conf/workflow
    ports:
      - 9011:8080
    expose:
      - 8080
    volumes:
      - /data/ztb-sd/workflow-service:/logs
    networks:
      - ztb_net

  permission-service:
    image: 10.20.54.132:8000/ztb-sd/permission-service:latest
    restart: always
    container_name: permission-service
    env_file:
      - ./conf/common
      - ./conf/permission
    ports:
      - 9012:8080
    expose:
      - 8080
    volumes:
      - /data/ztb-sd/permission-service:/logs
    networks:
      - ztb_net

  sourcing-service:
    image: 10.20.54.132:8000/ztb-sd/sourcing-service:latest
    restart: always
    container_name: sourcing-service
    env_file:
      - ./conf/common
      - ./conf/sourcing
    ports:
      - 9013:8080
    expose:
      - 8080
    volumes:
      - /data/ztb-sd/sourcing-service:/logs
    networks:
      - ztb_net

  vendor-service:
    image: 10.20.54.132:8000/ztb-sd/vendor-service:latest
    restart: always
    container_name: vendor-service
    env_file:
      - ./conf/common
      - ./conf/vendor
    ports:
      - 9014:8080
    expose:
      - 8080
    volumes:
      - /data/ztb-sd/vendor-service:/logs
    networks:
      - ztb_net

  vendor-perm-service:
    image: 10.20.54.132:8000/ztb-sd/vendor-perm-service:latest
    restart: always
    container_name: vendor-perm-service
    env_file:
      - ./conf/common
      - ./conf/vendor-perm
    ports:
      - 9015:8080
    expose:
      - 8080
    volumes:
      - /data/ztb-sd/vendor-perm-service:/logs
    networks:
      - ztb_net

  ztb-web:
    image: 10.20.54.132:8000/ztb-sd/ztb-web:latest
    restart: always
    container_name: ztb-web
    env_file:
      - ./conf/web
    expose:
      - 80
    networks:
      - ztb_net

  ztb-portal:
    image: 10.20.54.132:8000/ztb-sd/ztb-portal:latest
    restart: always
    container_name: ztb-portal
    env_file:
      - ./conf/portal
    expose:
      - 8081
    networks:
      - ztb_net

  scheduling-service:
    image: 10.20.54.132:8000/ztb-sd/scheduling-service:latest
    restart: always
    container_name: scheduling-service
#    ports:
#      - 8080:8080
    env_file:
      - ./conf/common
      - ./conf/scheduling
    expose:
      - 8080
    volumes:
      - /data/ztb-sd/scheduling-service:/logs
    networks:
      - ztb_net

  proxy:
    image: nginx:1.20.0
    container_name: proxy
    environment:
      - TZ=Asia/Shanghai
    restart: always
    ports:
      - 80:80
      - 81:81
      - 8080:8080
    volumes:
      - /data/ztb-sd/proxy/logs:/var/log/nginx
      - ./conf/proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ztb_net

networks:
  ztb_net:
    external: true
